apiVersion: v1
kind: Secret
metadata:
  name: csr-signer-signer
  namespace: openshift-kube-controller-manager-operator
  annotations:
    "auth.openshift.io/certificate-not-before": {{ .Assets | load "kubelet-signer.crt" | notBefore }}
    "auth.openshift.io/certificate-not-after": {{ .Assets | load "kubelet-signer.crt" | notAfter }}
    "auth.openshift.io/certificate-issuer": {{ .Assets | load "kubelet-signer.crt" | issuer }}
    "openshift.io/owning-component": "kube-controller-manager"
type: kubernetes.io/tls
data:
  tls.crt: {{ .Assets | load "kubelet-signer.crt" | base64 }}
  tls.key: {{ .Assets | load "kubelet-signer.key" | base64 }}
